name: Project Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' 

      - name: Install kaggle module
        run: |
          python -m pip install kaggle

      - name: Run tests
        run: |
          chmod +x project/tests.sh  
          ./project/tests.sh 
