name: Run Tests

on:
    push:
        paths:
            - data/**
            - project/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./data/requirements.txt  
          
      - name: Set Kaggle configuration
        run: |
          mkdir ~/.kaggle
          echo "$KAGGLE_USERNAME" > ~/.kaggle/kaggle.json
          echo "$KAGGLE_KEY" >> ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Run tests
        run: |
          cd project
          chmod +x tests.sh
          ./tests.sh  
