name: Project Feedback

on:
  push:
    branches:
    - main
    paths:
    - project/**

jobs:
  Project-feedback:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main

    - name: Checkout Project feedback
      uses: actions/checkout@v3
      with:
        repository: 123harshil/made-template

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'

    # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Run Project feedback
    - name: Project feedback
      run: |
        .blob/main/project/test.sh
