name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set execute permissions for test.py
        run: chmod +x project/test.py  # Ensure test.sh is executable within your repository structure

      - name: Run tests
        run: ./project/test.py
