name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          chmod +x test.sh  # Ensure test.sh is executable
          https://github.com/123harshil/made-template/blob/main/project/test.sh
